services:
  watchtower:
    image: containrrr/watchtower
    command: --label-enable --interval 30 --cleanup
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    build:
      context: "./"
      target: frontend
      args:
        - PROJECT=client-tg
        - VITE_API_SERVER=${VITE_API_SERVER}
    image: "rem4d/client-tg:stage"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - VITE_API_SERVER=${VITE_API_SERVER}
      - VITE_ROLLBAR_API_TOKEN=${VITE_ROLLBAR_API_TOKEN}
    stdin_open: true
    tty: true

  backend:
    build:
      context: "./"
      target: backend
      args:
        PROJECT: client-backend
    image: "rem4d/client-backend:stage"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: backend
    depends_on:
      - redis_db
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - REDIS_URL=redis://redis_db:6379

  redis_db:
    image: redis:alpine
    ports:
      - 6379:6379
