export const noIssuesTest = {
  text: "前田さんの年は三十九です。",
  expectedTokens: [
    {
      original: "前田",
      reading: "まえだ",
      start: 0,
      end: 2,
      pos: "noun",
      pos_detail_1: "proper_noun",
      pos_detail_2: "人名",
      basic_form: "前田",
      is_kanji: true,
      is_kana: false,
    },
    {
      original: "さん",
      reading: "さん",
      start: 2,
      end: 4,
      pos: "noun",
      pos_detail_1: "suffix",
      pos_detail_2: "人名",
      basic_form: "さん",
      is_kanji: false,
      is_kana: true,
    },
    {
      original: "の",
      reading: "の",
      start: 4,
      end: 5,
      pos: "particle",
      pos_detail_1: "連体化",
      pos_detail_2: "*",
      basic_form: "の",
      is_kanji: false,
      is_kana: true,
    },
    {
      original: "年",
      reading: "とし",
      start: 5,
      end: 6,
      pos: "noun",
      pos_detail_1: "common",
      pos_detail_2: "*",
      basic_form: "年",
      is_kanji: true,
      is_kana: false,
    },
    {
      original: "は",
      reading: "は",
      start: 6,
      end: 7,
      pos: "particle",
      pos_detail_1: "係助詞",
      pos_detail_2: "*",
      basic_form: "は",
      is_kanji: false,
      is_kana: true,
    },
    {
      original: "三",
      reading: "さん",
      start: 7,
      end: 8,
      pos: "noun",
      pos_detail_1: "number",
      pos_detail_2: "*",
      basic_form: "三",
      is_kanji: true,
      is_kana: false,
    },
    {
      original: "十",
      reading: "じゅう",
      start: 8,
      end: 9,
      pos: "noun",
      pos_detail_1: "number",
      pos_detail_2: "*",
      basic_form: "十",
      is_kanji: true,
      is_kana: false,
    },
    {
      original: "九",
      reading: "きゅう",
      start: 9,
      end: 10,
      pos: "noun",
      pos_detail_1: "number",
      pos_detail_2: "*",
      basic_form: "九",
      is_kanji: true,
      is_kana: false,
    },
    {
      original: "です",
      reading: "です",
      start: 10,
      end: 12,
      pos: "auxiliary",
      pos_detail_1: "*",
      pos_detail_2: "*",
      basic_form: "です",
      is_kanji: false,
      is_kana: true,
    },
    {
      original: "。",
      reading: "。",
      start: 12,
      end: 13,
      pos: "symbol",
      pos_detail_1: "full_stop",
      pos_detail_2: "*",
      basic_form: "。",
      is_kanji: false,
      is_kana: false,
    },
  ],
};
